name: Express Server CI/CD Workflow

on:
  push:
    branches: ["@dilshan"]

jobs:
  pull-postgres-image:
    runs-on: ubuntu-latest

    steps:
      - name: Pull PostgreSQL image
        run: docker pull postgres:18.1-alpine3.23

      - name: Verify PostgreSQL image
        run: docker images | grep postgres

      - name: Run PostgreSQL container
        run: |
          docker run -d --name postgres -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -p 5432:5432 postgres:18.1-alpine3.23

      - name: Check PostgreSQL container is running
        run: docker ps | grep postgres

  test:
    runs-on: ubuntu-latest
    needs: pull-postgres-image

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    env:
      DATABASE_URL: "postgresql://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/rest-api-db?schema=public"
      PORT: 8080

    steps:
      - name: Checkout code to runner
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.node-version }}"
      - name: Install dependencies
        run: npm install

      - name: Install prisma client
        run: npm install @prisma/client prisma

      - name: Migrate prisma schema
        run: npx prisma migrate dev --name init

      - name: Generate prisma client
        run: npx prisma generate

      - name: Check PORT 8080 using curl
        run: |
          npm start &
          sleep 5
          curl -f http://localhost:8080 || exit 1

  # build:
  #   runs-on: ubuntu-latest
  #   needs: test

  #   steps:
  #     - name: Checkout code to runner
  #       uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 18.x

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build the application
  #       run: npm run build
