name: Express Server CI/CD Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [22.x, 24.x]

    steps:
      - name: Hello World Action
        run: echo "Hello, world!"

      # - name: Checkout code to runner
      #   uses: actions/checkout@v2

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "${{ matrix.node-version }}"

      # - name: Install dependencies
      #   run: npm install

  # build:
  #   runs-on: ubuntu-latest
  #   needs: test

  #   steps:
  #     - name: Checkout code to runner
  #       uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 18.x

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build the application
  #       run: npm run build
